<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_proxy.proto

namespace GPBMetadata;

class RemoteProxy
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae2020a1272656d6f74655f70726f78792e70726f746f120b52656d6f74" .
            "6550726f7879226f0a06506172616d73120d0a05636c6173731801200128" .
            "09120c0a0466756e63180220012809120c0a046172677318032001280912" .
            "0c0a047061746818042001280912100a08686f73746e616d651805200128" .
            "09120d0a0564656c6179180620012805120b0a0371696418072001280322" .
            "360a055265706c79120f0a0773756363657373180120012808120f0a076d" .
            "657373616765180220012809120b0a03726964180320012803323d0a0843" .
            "6f6e73756d657212310a04776f726b12132e52656d6f746550726f78792e" .
            "506172616d731a122e52656d6f746550726f78792e5265706c792200323d" .
            "0a0850726f647563657212310a047075736812132e52656d6f746550726f" .
            "78792e506172616d731a122e52656d6f746550726f78792e5265706c7922" .
            "0042105a0e2e2f3b52656d6f746550726f7879620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

