<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_proxy.proto

namespace RemoteProxy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *请求参数
 *
 * Generated from protobuf message <code>RemoteProxy.Params</code>
 */
class Params extends \Google\Protobuf\Internal\Message
{
    /**
     *指定类
     *
     * Generated from protobuf field <code>string class = 1;</code>
     */
    protected $class = '';
    /**
     *指定方法
     *
     * Generated from protobuf field <code>string func = 2;</code>
     */
    protected $func = '';
    /**
     *参数
     *
     * Generated from protobuf field <code>string args = 3;</code>
     */
    protected $args = '';
    /**
     *执行位置
     *
     * Generated from protobuf field <code>string path = 4;</code>
     */
    protected $path = '';
    /**
     *消费者服务端口
     *
     * Generated from protobuf field <code>string hostname = 5;</code>
     */
    protected $hostname = '';
    /**
     *延迟消费时间
     *
     * Generated from protobuf field <code>int32 delay = 6;</code>
     */
    protected $delay = 0;
    /**
     *请求id
     *
     * Generated from protobuf field <code>int64 qid = 7;</code>
     */
    protected $qid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $class
     *          指定类
     *     @type string $func
     *          指定方法
     *     @type string $args
     *          参数
     *     @type string $path
     *          执行位置
     *     @type string $hostname
     *          消费者服务端口
     *     @type int $delay
     *          延迟消费时间
     *     @type int|string $qid
     *          请求id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RemoteProxy::initOnce();
        parent::__construct($data);
    }

    /**
     *指定类
     *
     * Generated from protobuf field <code>string class = 1;</code>
     * @return string
     */
    public function getClass()
    {
        return $this->class;
    }

    /**
     *指定类
     *
     * Generated from protobuf field <code>string class = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClass($var)
    {
        GPBUtil::checkString($var, True);
        $this->class = $var;

        return $this;
    }

    /**
     *指定方法
     *
     * Generated from protobuf field <code>string func = 2;</code>
     * @return string
     */
    public function getFunc()
    {
        return $this->func;
    }

    /**
     *指定方法
     *
     * Generated from protobuf field <code>string func = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFunc($var)
    {
        GPBUtil::checkString($var, True);
        $this->func = $var;

        return $this;
    }

    /**
     *参数
     *
     * Generated from protobuf field <code>string args = 3;</code>
     * @return string
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     *参数
     *
     * Generated from protobuf field <code>string args = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setArgs($var)
    {
        GPBUtil::checkString($var, True);
        $this->args = $var;

        return $this;
    }

    /**
     *执行位置
     *
     * Generated from protobuf field <code>string path = 4;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     *执行位置
     *
     * Generated from protobuf field <code>string path = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     *消费者服务端口
     *
     * Generated from protobuf field <code>string hostname = 5;</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     *消费者服务端口
     *
     * Generated from protobuf field <code>string hostname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     *延迟消费时间
     *
     * Generated from protobuf field <code>int32 delay = 6;</code>
     * @return int
     */
    public function getDelay()
    {
        return $this->delay;
    }

    /**
     *延迟消费时间
     *
     * Generated from protobuf field <code>int32 delay = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDelay($var)
    {
        GPBUtil::checkInt32($var);
        $this->delay = $var;

        return $this;
    }

    /**
     *请求id
     *
     * Generated from protobuf field <code>int64 qid = 7;</code>
     * @return int|string
     */
    public function getQid()
    {
        return $this->qid;
    }

    /**
     *请求id
     *
     * Generated from protobuf field <code>int64 qid = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQid($var)
    {
        GPBUtil::checkInt64($var);
        $this->qid = $var;

        return $this;
    }

}

