<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/.proto/message-platform.proto

namespace MessagePlatform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MessagePlatform.ModulePushParams</code>
 */
class ModulePushParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string module_key = 1;</code>
     */
    protected $module_key = '';
    /**
     * Generated from protobuf field <code>int32 channel_id = 2;</code>
     */
    protected $channel_id = 0;
    /**
     * Generated from protobuf field <code>repeated .MessagePlatform.AcceptUser accept_users = 3;</code>
     */
    private $accept_users;
    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     */
    protected $extra = '';
    /**
     *允许指定区域
     *
     * Generated from protobuf field <code>.MessagePlatform.Zone zone = 5;</code>
     */
    protected $zone = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $module_key
     *     @type int $channel_id
     *     @type \MessagePlatform\AcceptUser[]|\Google\Protobuf\Internal\RepeatedField $accept_users
     *     @type string $extra
     *     @type int $zone
     *          允许指定区域
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Proto\MessagePlatform::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string module_key = 1;</code>
     * @return string
     */
    public function getModuleKey()
    {
        return $this->module_key;
    }

    /**
     * Generated from protobuf field <code>string module_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModuleKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->module_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 channel_id = 2;</code>
     * @return int
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }

    /**
     * Generated from protobuf field <code>int32 channel_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setChannelId($var)
    {
        GPBUtil::checkInt32($var);
        $this->channel_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MessagePlatform.AcceptUser accept_users = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAcceptUsers()
    {
        return $this->accept_users;
    }

    /**
     * Generated from protobuf field <code>repeated .MessagePlatform.AcceptUser accept_users = 3;</code>
     * @param \MessagePlatform\AcceptUser[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAcceptUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MessagePlatform\AcceptUser::class);
        $this->accept_users = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     * @return string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkString($var, True);
        $this->extra = $var;

        return $this;
    }

    /**
     *允许指定区域
     *
     * Generated from protobuf field <code>.MessagePlatform.Zone zone = 5;</code>
     * @return int
     */
    public function getZone()
    {
        return $this->zone;
    }

    /**
     *允许指定区域
     *
     * Generated from protobuf field <code>.MessagePlatform.Zone zone = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setZone($var)
    {
        GPBUtil::checkEnum($var, \MessagePlatform\Zone::class);
        $this->zone = $var;

        return $this;
    }

}

