<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/.proto/message-platform.proto

namespace MessagePlatform;

use UnexpectedValueException;

/**
 * Protobuf type <code>MessagePlatform.Role</code>
 */
class Role
{
    /**
     *客户
     *
     * Generated from protobuf enum <code>PURCHASER = 0;</code>
     */
    const PURCHASER = 0;
    /**
     *客服
     *
     * Generated from protobuf enum <code>KEFU = 1;</code>
     */
    const KEFU = 1;
    /**
     *运营
     *
     * Generated from protobuf enum <code>MANAGER = 2;</code>
     */
    const MANAGER = 2;
    /**
     *供应商
     *
     * Generated from protobuf enum <code>SUPPLIER = 3;</code>
     */
    const SUPPLIER = 3;

    private static $valueToName = [
        self::PURCHASER => 'PURCHASER',
        self::KEFU => 'KEFU',
        self::MANAGER => 'MANAGER',
        self::SUPPLIER => 'SUPPLIER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

