<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/.proto/message-platform.proto

namespace MessagePlatform;

use UnexpectedValueException;

/**
 * Protobuf type <code>MessagePlatform.Space</code>
 */
class Space
{
    /**
     *未指定
     *
     * Generated from protobuf enum <code>SPACE_NONE = 0;</code>
     */
    const SPACE_NONE = 0;
    /**
     *珠海
     *
     * Generated from protobuf enum <code>ZH = 1;</code>
     */
    const ZH = 1;
    /**
     *澳门
     *
     * Generated from protobuf enum <code>MO = 2;</code>
     */
    const MO = 2;

    private static $valueToName = [
        self::SPACE_NONE => 'SPACE_NONE',
        self::ZH => 'ZH',
        self::MO => 'MO',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

