<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/.proto/message-platform.proto

namespace MessagePlatform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MessagePlatform.TokenParams</code>
 */
class TokenParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string zone = 1;</code>
     */
    protected $zone = '';
    /**
     * Generated from protobuf field <code>int32 role = 2;</code>
     */
    protected $role = 0;
    /**
     * Generated from protobuf field <code>int32 user_id = 3;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     */
    protected $extra = '';
    /**
     * Generated from protobuf field <code>.MessagePlatform.TokenType token_type = 5;</code>
     */
    protected $token_type = 0;
    /**
     * Generated from protobuf field <code>string platform_key = 6;</code>
     */
    protected $platform_key = '';
    /**
     * Generated from protobuf field <code>string sign = 7;</code>
     */
    protected $sign = '';
    /**
     * Generated from protobuf field <code>int32 at = 8;</code>
     */
    protected $at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $zone
     *     @type int $role
     *     @type int $user_id
     *     @type string $extra
     *     @type int $token_type
     *     @type string $platform_key
     *     @type string $sign
     *     @type int $at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Proto\MessagePlatform::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string zone = 1;</code>
     * @return string
     */
    public function getZone()
    {
        return $this->zone;
    }

    /**
     * Generated from protobuf field <code>string zone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setZone($var)
    {
        GPBUtil::checkString($var, True);
        $this->zone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 role = 2;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>int32 role = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkInt32($var);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 3;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     * @return string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkString($var, True);
        $this->extra = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MessagePlatform.TokenType token_type = 5;</code>
     * @return int
     */
    public function getTokenType()
    {
        return $this->token_type;
    }

    /**
     * Generated from protobuf field <code>.MessagePlatform.TokenType token_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTokenType($var)
    {
        GPBUtil::checkEnum($var, \MessagePlatform\TokenType::class);
        $this->token_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform_key = 6;</code>
     * @return string
     */
    public function getPlatformKey()
    {
        return $this->platform_key;
    }

    /**
     * Generated from protobuf field <code>string platform_key = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatformKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sign = 7;</code>
     * @return string
     */
    public function getSign()
    {
        return $this->sign;
    }

    /**
     * Generated from protobuf field <code>string sign = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->sign = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 at = 8;</code>
     * @return int
     */
    public function getAt()
    {
        return $this->at;
    }

    /**
     * Generated from protobuf field <code>int32 at = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->at = $var;

        return $this;
    }

}

