<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/.proto/message-platform.proto

namespace MessagePlatform;

use UnexpectedValueException;

/**
 * Protobuf type <code>MessagePlatform.TokenType</code>
 */
class TokenType
{
    /**
     *后台密钥
     *
     * Generated from protobuf enum <code>ADMIN = 0;</code>
     */
    const ADMIN = 0;
    /**
     *pusher密钥
     *
     * Generated from protobuf enum <code>PUSHER = 1;</code>
     */
    const PUSHER = 1;

    private static $valueToName = [
        self::ADMIN => 'ADMIN',
        self::PUSHER => 'PUSHER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

