<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/.proto/pusher.proto

namespace Pusher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *请求参数
 *
 * Generated from protobuf message <code>Pusher.MessageParams</code>
 */
class MessageParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>string data = 4;</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>string jump = 5;</code>
     */
    protected $jump = '';
    /**
     * Generated from protobuf field <code>string app = 6;</code>
     */
    protected $app = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $channel
     *     @type string $title
     *     @type string $content
     *     @type string $data
     *     @type string $jump
     *     @type string $app
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Proto\Pusher::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 4;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jump = 5;</code>
     * @return string
     */
    public function getJump()
    {
        return $this->jump;
    }

    /**
     * Generated from protobuf field <code>string jump = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setJump($var)
    {
        GPBUtil::checkString($var, True);
        $this->jump = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app = 6;</code>
     * @return string
     */
    public function getApp()
    {
        return $this->app;
    }

    /**
     * Generated from protobuf field <code>string app = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setApp($var)
    {
        GPBUtil::checkString($var, True);
        $this->app = $var;

        return $this;
    }

}

