<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/.proto/pusher.proto

namespace Pusher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Pusher.ReadParams</code>
 */
class ReadParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ids = 1;</code>
     */
    protected $ids = '';
    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>string app = 3;</code>
     */
    protected $app = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ids
     *     @type string $channel
     *     @type string $app
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Proto\Pusher::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ids = 1;</code>
     * @return string
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * Generated from protobuf field <code>string ids = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app = 3;</code>
     * @return string
     */
    public function getApp()
    {
        return $this->app;
    }

    /**
     * Generated from protobuf field <code>string app = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setApp($var)
    {
        GPBUtil::checkString($var, True);
        $this->app = $var;

        return $this;
    }

}

